/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        pink: {
          50: "var(--color-cream)",
          100: "var(--color-warm)",
          200: "var(--color-sand)",
          300: "#D6BE95",
          400: "#BF9454",
          500: "var(--color-caramel)",
          600: "#A06F2F",
          700: "#845728",
          800: "var(--color-brown-dark)",
          900: "#3D281D",
        },
        cyan: {
          50: "#F4F8F3",
          100: "#E8F0E6",
          200: "#CFE0CB",
          300: "#AFC8A8",
          400: "#90B38A",
          500: "var(--color-sage)",
          600: "#658861",
          700: "#4E6D4A",
          800: "#3B5239",
          900: "#2A3A29",
        },
        sky: {
          50: "#FFF8EC",
          100: "#FCEFD7",
          200: "#F6DBAC",
          300: "#EFC77F",
          400: "#E0AD55",
          500: "var(--color-caramel)",
          600: "#A67A2E",
          700: "#825F26",
          800: "#60461E",
          900: "#3F3016",
        },
        emerald: {
          50: "#F6F8F2",
          100: "#E8EEDF",
          200: "#D1DEC1",
          300: "#B5C89D",
          400: "#93AB79",
          500: "var(--color-forest)",
          600: "#2F4730",
          700: "#233625",
          800: "#1A281C",
          900: "#131E14",
        },
        warm: "var(--color-warm)",
        cream: "var(--color-cream)",
        sand: "var(--color-sand)",
        caramel: "var(--color-caramel)",
        "accent-caramel": "var(--color-accent-caramel)",
        brown: "var(--color-brown)",
        "brown-dark": "var(--color-brown-dark)",
        forest: "var(--color-forest)",
        "accent-forest": "var(--color-accent-forest)",
        sage: "var(--color-sage)",
        blush: "var(--color-blush)",
        rust: "var(--color-rust)",
        ink: "var(--color-ink)",
        "text-ink": "var(--color-text-ink)",
        muted: "var(--color-muted)",
        "text-nav": "var(--color-text-nav)",
        "brown-button": "var(--color-brown-button)",
        "brown-logo": "var(--color-brown-logo)",
        "badge-warm": "var(--color-badge-warm)",
      },
      fontFamily: {
        serif: ["var(--font-serif)"],
        sans: ["var(--font-sans)"],
      },
      borderRadius: {
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      keyframes: {
        float: {
          '0%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-12px) ' },
          '100%': { transform: 'translateY(0)' },
        }
      },
      animation: {
        float: 'float 4s ease-in-out infinite',
      }
    },
  },
  plugins: [],
}
